#*****************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# zybo_dummyTxRx.tcl: Tcl script for re-creating project 'zybo_dummy_txrx'
#
# Generated by Vivado on Wed May 18 06:13:39 -0500 2022
# IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (zybo_dummyTxRx.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/bd/design_1/design_1.bd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/AxiLiteSlaveSimple.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixPkg.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/UartRx.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/UartTx.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/UartTop.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixEndeavorRx.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixEndeavorTx.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixEndeavorTop.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixAsicDummyTop.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixAsicDummyTop.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixDaqCtrlDummy.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixProtoPkg.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixProtoPkg.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/bd/design_1/hdl/design_1_wrapper.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixProtoRegMap.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixTxRxTestTop.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/mem.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqCtrl.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QpixDummyTxRx.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/StdRtlPkg.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/FifoOutputPipeline.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/SimpleDualPortRam.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/FifoSync.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixTestPatGen.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixDataProc.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixParser.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixComm.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixRegFile.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/EdgeDetector.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixRoute.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixAsicTop.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/imp/QpixAsicArray.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/UtilityPkg.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqHub.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqNode.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixDummyTxRx.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/QpixHitsGen.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/imp/QpixUtilTest.vhd"
#    "C:/Users/keefe/Documents/research/main_qpix-digital/qpix-digital/firmware/src/UartClockGenerator.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/xdc/qpix.xdc"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/sim/slac-surf/ClkRst.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/sim/qpix_dummy_sim_TB.vhd"
#    "C:/Users/keefe/Documents/vivado_projects/QpixQDB/hdl/QDBAsicTop.vhd"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "zybo_dummy_txrx"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "zybo_dummyTxRx.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../work/zybo_dummy_txrx"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "digilentinc.com:zybo-z7-20:part0:1.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.board_id" -value "zybo-z7-20" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.uses_pr" -value "1" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "2" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "2" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "2" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "2" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "36" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../bd/design_1/design_1.bd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/AxiLiteSlaveSimple.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixPkg.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartRx.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartTx.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartTop.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixEndeavorRx.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixEndeavorTx.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixEndeavorTop.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixAsicDummyTop.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixAsicDummyTop.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixDaqCtrlDummy.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixProtoPkg.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixProtoPkg.vhd"] \
 [file normalize "${origin_dir}/../bd/design_1/hdl/design_1_wrapper.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixProtoRegMap.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixTxRxTestTop.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/mem.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqCtrl.vhd"] \
 [file normalize "${origin_dir}/../hdl/QpixDummyTxRx.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/StdRtlPkg.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/FifoOutputPipeline.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/SimpleDualPortRam.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/FifoSync.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixTestPatGen.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDataProc.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixParser.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixComm.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixRegFile.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/EdgeDetector.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixRoute.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixAsicTop.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/imp/QpixAsicArray.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/UtilityPkg.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqHub.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqNode.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDummyTxRx.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixHitsGen.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/imp/QpixUtilTest.vhd"] \
 [file normalize "${origin_dir}/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartClockGenerator.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../bd/design_1/design_1.bd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "registered_with_manager" -value "1" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/AxiLiteSlaveSimple.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../hdl/QpixPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../hdl/QpixEndeavorRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../hdl/QpixEndeavorTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../hdl/QpixEndeavorTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixAsicDummyTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../hdl/QpixAsicDummyTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../hdl/QpixDaqCtrlDummy.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixProtoPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../hdl/QpixProtoPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../bd/design_1/hdl/design_1_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../hdl/QpixProtoRegMap.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../hdl/QpixTxRxTestTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/mem.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqCtrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../hdl/QpixDummyTxRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/StdRtlPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/FifoOutputPipeline.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/SimpleDualPortRam.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/slac-surf/FifoSync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixTestPatGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDataProc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixParser.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixComm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixRegFile.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/EdgeDetector.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixRoute.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixAsicTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/imp/QpixAsicArray.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/UtilityPkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqHub.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDaqNode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixDummyTxRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/QpixHitsGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/imp/QpixUtilTest.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../../../research/main_qpix-digital/qpix-digital/firmware/src/UartClockGenerator.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "QpixTxRxTestTop" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../xdc/qpix.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../xdc/qpix.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/../xdc/qpix.xdc"]" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/../xdc/qpix.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/../sim/slac-surf/ClkRst.vhd"] \
 [file normalize "${origin_dir}/../sim/qpix_dummy_sim_TB.vhd"] \
 [file normalize "${origin_dir}/../hdl/QDBAsicTop.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../sim/slac-surf/ClkRst.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../sim/qpix_dummy_sim_TB.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj

set file "$origin_dir/../hdl/QDBAsicTop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "qpix_qdb_sim_TB" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg400-1 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg400-1 -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
